all: ljmd

CC = cl
CFLAGS = -O2

ljmd: initialize.obj integrate.obj neighbor.obj force.obj memory.obj main.obj
	$(CC) -o ljmd \
	initialize.obj integrate.obj neighbor.obj force.obj memory.obj main.obj

initialize.obj: initialize.cpp
	$(CC) $(CFLAGS) -c initialize.cpp
integrate.obj: integrate.cpp
	$(CC) $(CFLAGS) -c integrate.cpp
memory.obj: memory.cpp
	$(CC) $(CFLAGS) -c memory.cpp
neighbor.obj: neighbor.cpp
	$(CC) $(CFLAGS) -c neighbor.cpp
force.obj: force.cpp
	$(CC) $(CFLAGS) -c force.cpp
main.obj: main.cpp
	$(CC) $(CFLAGS) -c main.cpp

clean:
	del *obj ljmd*
